name: a
on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: ^1.16
            id: go
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building
        run: go build -v -o hello-world .
